FROM nginx:1.17.6-alpine

COPY nginx.conf /etc/nginx/nginx.conf
COPY templates /templates

COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT [ "/docker-entrypoint.sh" ]
