FROM nginx:1.13.6-alpine

COPY templates /templates
COPY config/custom.conf /etc/nginx/conf.d/custom.conf
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT [ "/docker-entrypoint.sh" ]
