location ~ ${NGINX_SUBFOLDER}/(.*) {
   try_files /$1 @rewrite;
}

location ${NGINX_SUBFOLDER} {
  if ($http_x_forwarded_proto = "https") {
    return 301 https://$host$request_uri/;
  }
  return 301 http://$host$request_uri/;
}
